### ISSUE TITLE
Tests fail to compile on GHC 8.6.1

### ISSUE THREAD

**Issue by jkachmar** [adinapoli/cuckoofilter#1]
`cuckoo-filter`'s test suite currently fails to compile on GHC 8.6.1 with the following error:

```
test/Spec.hs:23:9: error:
    • No instance for (Control.Monad.Fail.MonadFail
                         Data.Functor.Identity.Identity)
        arising from a do statement
        with the failable pattern ‘Just f’
    • In a stmt of a 'do' block: Just f <- insert defaultFilter s
      In the second argument of ‘($)’, namely
        ‘do Just f <- insert defaultFilter s
            f' <- delete f s
            not <$> member s f'’
      In the expression:
        runIdentity
          $ do Just f <- insert defaultFilter s
               f' <- delete f s
               not <$> member s f'
   |
23 |         Just f <- insert defaultFilter s
   |  
```

**Comment by ChrisCoffey** [comment]
I believe this is for [ChrisCoffey/cuckoo-filter](https://github.com/ChrisCoffey/cuckoo-filter) rather than this repo.
